name: med_card
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2

  go_router: ^13.2.0

  equatable: ^2.0.5

  chopper: ^7.0.8

  flutter_bloc: ^8.1.3

  flutter_screenutil: ^5.9.0

  flutter_svg: ^2.0.9

  http: ^1.1.0

  hive:

  hive_flutter:

  json_annotation: 4.8.1

  logging: ^1.2.0

  shimmer: ^3.0.0

  better_player: ^0.0.83

  # #downloader feature starts here
  # flutter_downloader: 1.11.4

  # percent_indicator: ^4.2.3

  # permission_handler: ^11.0.1

  # open_file: ^3.3.2

  # path_provider: ^2.1.1
  # #end here

  flutter_gen: ^5.3.2

  url_launcher: ^6.1.14

  # package_info_plus: ^4.2.0

  share_plus: ^6.3.4

  bot_toast: ^4.1.3

  intl: ^0.18.1

  flutter_dialogs: ^3.0.0

  percent_indicator: ^4.2.3

  fl_chart: ^0.64.0










dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.6

  chopper_generator: ^7.0.6

  json_serializable: ^6.7.1

  hive_generator:

  flutter_gen_runner: ^5.3.2


flutter_gen:
  output: lib/gen/ 
  line_length: 80 

  # Optional
  integrations:
    flutter_svg: true
    rive: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/stores/
    - assets/icons/
    - assets/icons/downloader/
    - assets/icons/home_tab_icons/
    - assets/icons/figma_icons/
    - assets/icons/figma_icons/
    - assets/icons/specialties/
    
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf

  # water_drop_nav_bar: ^2.2.1 got bottom nav_bar from here
